version: '3.5'
services: 
  nginx:
    image: nginx
    ports:
      - 80:80
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.hostname == swarmvm1]
